# Generated by Django 4.2.17 on 2025-01-11 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0004_rename_category_servercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='server_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
